export MLFLOW_TRACKING_URI="REPLACE_ME_WITH_YOUR_MLFLOW_TRACKING_URI"
export AWS_ACCESS_KEY_ID="REPLACE_ME_WITH_YOUR_AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="REPLACE_ME_WITH_YOUR_AWS_SECRET_ACCESS_KEY"
export BACKEND_STORE_URI="REPLACE_ME_WITH_YOUR_BACKEND_STORE_URI" # That one is optional if you didn't set it above
export ARTIFACT_ROOT="REPLACE_ME_WITH_YOUR_ARTIFACT_ROOT" # That one is optional if you didn't set it above
